eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8988

spring:
  application:
    # This ends up as the service name in zipkin
    name: service-hi
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
     baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

#sample:
#  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
#    enabled: true